Issue #SB-30124 fix: Enable "Create New" functionality for editors
Sunbird-Knowlg/knowlg-portal pull request #14
Opened 2022-06-13 09:54 UTC by vaibhavbhuva

2022-06-14 03:57 UTC, vinukumar-vs requested changes
There is no unit-test cases for create new functionality..

2022-06-14 04:06 UTC, vinukumar-vs requested changes
Use Rxjs for API request to combine or to call parallel

2022-06-14 04:06 UTC, vinukumar-vs commented on src/app/editors/collection-editor/collection-editor.component.ts
> +    if (this.queryParams.identifier) {
This if condition should go ngOnInit function.

2022-06-14 04:06 UTC, vinukumar-vs commented on src/app/editors/collection-editor/collection-editor.component.ts
> +        this.getFrameWorkDetails();
Why this is called here in sequence & why are we waiting till the channel response?

2022-06-14 04:06 UTC, vinukumar-vs commented on src/app/editors/collection-editor/collection-editor.component.ts
> +    this.helperService.getCategoryDefinition('Collection', this.content.primaryCategory, this.content.channel)
Use Rxjs to combine the requests in parallel or sequence.

2022-06-14 16:14 UTC, vaibhavbhuva commented
@vinukumar-vs All the comments have been resolved.

2022-06-16 05:52 UTC, vinukumar-vs approved these changes

2022-06-16 05:52 UTC, merged