Issue #KN-310 feat: Updated the collection editor package version
Sunbird-Knowlg/knowlg-portal pull request #67
Opened 2022-09-28 09:12 UTC by vaibhavbhuva

2022-09-28 09:25 UTC, vinukumar-vs requested changes

2022-09-28 09:25 UTC, vinukumar-vs commented on package.json
> +    "@project-sunbird/sunbird-quml-player": "5.1.1",
WHy QuML player is added to Knowledge portal?

2022-09-28 09:53 UTC, vaibhavbhuva commented on package.json
> +    "@project-sunbird/sunbird-quml-player": "5.1.1",
@vinukumar-vs QuML player is the dependencies of the collection editor and both Collection & QuestionSet editors are using a single code base. hence we need to add  it in the knowlg-portal.

2022-09-29 05:11 UTC, vinukumar-vs approved these changes

2022-09-29 05:27 UTC, merged