Issue #KN-316 feat: Pdf player: web component implementation for knowlg app
Sunbird-Knowlg/knowlg-portal pull request #73
Opened 2022-10-19 11:26 UTC by santoshilimi

2022-10-19 12:13 UTC, HarishGangula requested changes
How come without changing the player usage as a web component, it is working?
Expected changes to be done player component in shared module to use pdf player web component, So there are some reference of the pdf player angular module check and remove that

2022-10-20 05:19 UTC, HarishGangula approved these changes

2022-10-25 04:59 UTC, vinukumar-vs reviewed
Why pdfjs library is added under assets folder?  
All images are span across the different folders. There is not propert folder structure for images.
Assets have lot of different files like images, locales, JS, CSS, HTML. Move the library to libs foder & under the assets keep proper folder structure like images, CSS if needed.

2022-10-31 04:58 UTC, vinukumar-vs reviewed
As discussed, player component will get replace with Share Common-player component. So that player logic will not be present in any portal or mobile integration.

Abstract out the player identification logic from implementation side.

2022-10-31 04:59 UTC, vinukumar-vs approved these changes

2022-10-31 04:59 UTC, merged