Issue #KN-298 feat: Show list of contents for consumptions experiences
Sunbird-Knowlg/knowlg-portal pull request #94
Opened 2022-12-11 12:34 UTC by gouravmore

Issue #KN-298 feat: Show list of contents for consumptions experiences
Demo link:- https://drive.google.com/file/d/1V-rIy_i1bwBUiE5HNXAst32mn1e67gY3/view?usp=drivesdk

2022-12-21 06:35 UTC, HarishGangula requested changes
Share the Demo video covering all the scenarios

2022-12-21 06:57 UTC, gouravmore commented
@HarishGangula Updated the Demo video link in the description 
Link:- https://drive.google.com/file/d/1DMjLOrMNkcrtSkftD4PbKPDVX170AOKG/view?usp=drivesdk

2022-12-23 06:32 UTC, HarishGangula approved these changes

2022-12-28 05:23 UTC, vinukumar-vs approved these changes

2022-12-28 05:23 UTC, merged